"""add personal use AI solutions count

Revision ID: a16a0e32c0e9
Revises: dafe5aec9fa8
Create Date: 2026-08-18 12:52:27.793958
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a16a0e32c0e9'
down_revision: Union[str, None] = 'dafe5aec9fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department_scores', sa.Column('ai_solutions_personal', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
