"""add agent and automation indicators

Revision ID: dafe5aec9fa8
Revises: e45dfe888bee
Create Date: 2026-08-18 11:49:53.788617
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dafe5aec9fa8'
down_revision: Union[str, None] = 'e45dfe888bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department_scores', sa.Column('agent', sa.Float(), nullable=False, server_default='0'))
    op.add_column('department_scores', sa.Column('automate', sa.Float(), nullable=False, server_default='0'))
    op.add_column('department_scores', sa.Column('ai_solutions', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department_scores', 'ai_solutions')
    op.drop_column('department_scores', 'automate')
    op.drop_column('department_scores', 'agent')
    # ### end Alembic commands ###
